### ISSUE TITLE
Where does the name comes from? 

### ISSUE THREAD

**Issue by jdeniau** [tstyche/tstyche.org#2]
Since you mention tstyche, there is one thing that bothers me : what does "tyche" means?

Is it related to https://en.wikipedia.org/wiki/Tyche?

If it is, it might be interesting to mention it in the documentation or the Readme file maybe?

**Comment by mrazauskas** [comment]
A new Introduction page just got added: https://tstyche.org/guide/introduction

All is explained here. Thanks again for the idea!
